### ISSUE TITLE
Saturation set to 1% when changing color

### ISSUE THREAD

**Issue by Black-Lemon** [AlCalzone/ioBroker.tradfri#44]
When I change the value for color, the value for saturation is automaticaly changed to 1% (and so it's white)

ioBroker.admin 3.2.3
tradfri 1.07

**Comment by AlCalzone** [comment]
This should be fixed in the newer versions (>=1.1.6). I'm going to push the current version to stable.

**Comment by AlCalzone** [comment]
Once https://github.com/ioBroker/ioBroker.repositories/pull/102 is merged, you should be good to go

**Comment by Black-Lemon** [comment]
my mistake in my first post: i got 1.**1**.7 installed. and it's not working.

it was working with ioBrokerAdmin 3.x and tradfri 1.x. Then some updates came out and it stopped working for me. I tried downgrading admin and tradfri but couldn't get it to work anymore. Saturation is always reseted. Sadly I don't know with when exactly it broke :( Could some other adapters interfere? (I got fritzbox, sonoff, pushover, yahka and javascript installed)

**Comment by AlCalzone** [comment]
Hmm, then I need some additional info:

1. The versions of the underlying libs:
```
cd /opt/iobroker
npm ls | grep node-*-client
```

2. A log from the adapter with adapter log level set to "debug" in the instances tab (expert mode) when you set those values

3. The values of the colors you're trying to set and the resulting hue/sat.

**Comment by Black-Lemon** [comment]
1:

root@raspberrypi:/opt/iobroker# npm ls | grep node-*-client
npm ERR! missing: iobroker.admin@~3.1.12, required by iobroker.inst@1.0.8
npm ERR! extraneous: async-limiter@1.0.0 /opt/iobroker/node_modules/async-limiter
npm ERR! extraneous: connect-flash@0.1.1 /opt/iobroker/node_modules/connect-flash
npm ERR! extraneous: dev-null@0.1.1 /opt/iobroker/node_modules/dev-null
npm ERR! extraneous: express@4.16.2 /opt/iobroker/node_modules/express
npm ERR! extraneous: express-fileupload@0.4.0 /opt/iobroker/node_modules/express-fileupload
npm ERR! extraneous: express-session@1.15.6 /opt/iobroker/node_modules/express-session
npm ERR! extraneous: hap-nodejs@0.4.41 /opt/iobroker/node_modules/hap-nodejs
npm ERR! extraneous: has-binary2@1.0.2 /opt/iobroker/node_modules/has-binary2
npm ERR! extraneous: iobroker.feiertage@1.0.0 /opt/iobroker/node_modules/iobroker.feiertage
npm ERR! extraneous: iobroker.fritzbox@0.3.1 /opt/iobroker/node_modules/iobroker.fritzbox
npm ERR! extraneous: iobroker.javascript@3.6.4 /opt/iobroker/node_modules/iobroker.javascript
npm ERR! extraneous: iobroker.pushover@1.0.4 /opt/iobroker/node_modules/iobroker.pushover
npm ERR! extraneous: iobroker.simple-api@1.6.2 /opt/iobroker/node_modules/iobroker.simple-api
npm ERR! extraneous: iobroker.socketio@1.8.6 /opt/iobroker/node_modules/iobroker.socketio
npm ERR! extraneous: iobroker.sonoff@1.0.2 /opt/iobroker/node_modules/iobroker.sonoff
npm ERR! extraneous: iobroker.tr-064@0.4.18 /opt/iobroker/node_modules/iobroker.tr-064
npm ERR! extraneous: iobroker.tradfri@1.1.7 /opt/iobroker/node_modules/iobroker.tradfri
npm ERR! extraneous: iobroker.yahka@0.7.1 /opt/iobroker/node_modules/iobroker.yahka
npm ERR! extraneous: macaddress@0.2.8 /opt/iobroker/node_modules/macaddress
npm ERR! extraneous: mqtt-connection@3.2.0 /opt/iobroker/node_modules/mqtt-connection
npm ERR! extraneous: node-tradfri-client@0.8.1 /opt/iobroker/node_modules/node-tradfri-client
npm ERR! extraneous: passport@0.4.0 /opt/iobroker/node_modules/passport
npm ERR! extraneous: passport-local@1.0.0 /opt/iobroker/node_modules/passport-local
npm ERR! extraneous: passport.socketio@3.7.0 /opt/iobroker/node_modules/passport.socketio
npm ERR! extraneous: pushover-notifications@0.2.4 /opt/iobroker/node_modules/pushover-notifications
npm ERR! extraneous: soef@0.4.15 /opt/iobroker/node_modules/soef
npm ERR! extraneous: tr-064@0.2.0 /opt/iobroker/node_modules/tr-064
npm ERR! extraneous: tr-O64@0.2.4 /opt/iobroker/node_modules/tr-O64
npm ERR! extraneous: util@0.10.3 /opt/iobroker/node_modules/util
npm ERR! extraneous: uws@9.14.0 /opt/iobroker/node_modules/uws


2.
I just tried ff0000, 00ff00, 0000ff for testing. Color gets set but saturation changes to 1%.

This happens, wenn iI go to Objekte (on ioBroker Admin) → tradfri.0 → L-xxxxxx → lightbulb → color and chance the value manually or by JavaScript like:
setState("tradfri.0.L-65537.lightbulb.color", 'ff00ff');



3.



tradfri.0 | 2018-03-07 13:04:58.912 | debug | ping successful...
-- | -- | -- | --
tradfri.0 | 2018-03-07 13:04:48.861 | debug | ping successful...
tradfri.0 | 2018-03-07 13:04:45.057 | debug | state with id tradfri.0.G-131073.state updated: ack=true; val=true
tradfri.0 | 2018-03-07 13:04:45.043 | debug | state with id tradfri.0.G-131073.brightness updated: ack=true; val=100
tradfri.0 | 2018-03-07 13:04:45.031 | debug | state with id tradfri.0.G-131073.saturation updated: ack=true; val=1
tradfri.0 | 2018-03-07 13:04:45.021 | debug | state with id tradfri.0.G-131073.hue updated: ack=true; val=0
tradfri.0 | 2018-03-07 13:04:44.968 | debug | state with id tradfri.0.G-131073.color updated: ack=true; val=ff0000
tradfri.0 | 2018-03-07 13:04:44.728 | debug | state with id tradfri.0.L-65537.lightbulb.transitionDuration updated: ack=true; val=0.5
tradfri.0 | 2018-03-07 13:04:44.724 | debug | state with id tradfri.0.L-65537.lightbulb.state updated: ack=true; val=true
tradfri.0 | 2018-03-07 13:04:44.721 | debug | state with id tradfri.0.L-65537.lightbulb.brightness updated: ack=true; val=100
tradfri.0 | 2018-03-07 13:04:44.717 | debug | state with id tradfri.0.L-65537.lightbulb.saturation updated: ack=true; val=1
tradfri.0 | 2018-03-07 13:04:44.704 | debug | state with id tradfri.0.L-65537.lightbulb.hue updated: ack=true; val=0
tradfri.0 | 2018-03-07 13:04:44.699 | debug | state with id tradfri.0.L-65537.lightbulb.color updated: ack=true; val=ff0000
tradfri.0 | 2018-03-07 13:04:44.694 | debug | state with id tradfri.0.L-65537.lastSeen updated: ack=true; val=1520391679
tradfri.0 | 2018-03-07 13:04:44.681 | debug | state with id tradfri.0.L-65537.alive updated: ack=true; val=true
tradfri.0 | 2018-03-07 13:04:44.645 | debug | observeDevice > {"3":{"0":"IKEA of Sweden","1":"TRADFRI bulb E27 CWS opal 600lm","2":"","3":"1.3.002","6":1},"3311":[{"5706":"0","5707":0,"5708":653,"5709":20514,"5710":21477,"5850":1,"5851":254,"900
tradfri.0 | 2018-03-07 13:04:44.631 | debug | updateResource(15001/65537) > sending payload: {"3311":[{"5707":0,"5708":653,"5712":5}]}
tradfri.0 | 2018-03-07 13:04:44.596 | debug | updateResource(15001/65537) > comparing {"isProxy":true,"options":{},"name":"Nachttischlampe","createdAt":1510764428,"instanceId":65537,"type":2,"deviceInfo":{"isProxy":true,"options":{},"firmwareVer
tradfri.0 | 2018-03-07 13:04:44.539 | debug | state with id tradfri.0.L-65537.lightbulb.color updated: ack=false; val=ff0000
tradfri.0 | 2018-03-07 13:04:38.862 | debug | ping successful...
tradfri.0 | 2018-03-07 13:04:37.313 | debug | state with id tradfri.0.G-131073.state updated: ack=true; val=true
tradfri.0 | 2018-03-07 13:04:37.305 | debug | state with id tradfri.0.G-131073.brightness updated: ack=true; val=100
tradfri.0 | 2018-03-07 13:04:37.291 | debug | state with id tradfri.0.G-131073.saturation updated: ack=true; val=100
tradfri.0 | 2018-03-07 13:04:37.284 | debug | state with id tradfri.0.G-131073.hue updated: ack=true; val=240
tradfri.0 | 2018-03-07 13:04:37.256 | debug | state with id tradfri.0.G-131073.color updated: ack=true; val=0000ff
tradfri.0 | 2018-03-07 13:04:37.021 | debug | state with id tradfri.0.L-65537.lightbulb.transitionDuration updated: ack=true; val=0.5
tradfri.0 | 2018-03-07 13:04:37.013 | debug | state with id tradfri.0.L-65537.lightbulb.state updated: ack=true; val=true
tradfri.0 | 2018-03-07 13:04:37.009 | debug | state with id tradfri.0.L-65537.lightbulb.brightness updated: ack=true; val=100
tradfri.0 | 2018-03-07 13:04:37.005 | debug | state with id tradfri.0.L-65537.lightbulb.saturation updated: ack=true; val=100
tradfri.0 | 2018-03-07 13:04:37.001 | debug | state with id tradfri.0.L-65537.lightbulb.hue updated: ack=true; val=240
tradfri.0 | 2018-03-07 13:04:36.988 | debug | state with id tradfri.0.L-65537.lightbulb.color updated: ack=true; val=0000ff
tradfri.0 | 2018-03-07 13:04:36.984 | debug | state with id tradfri.0.L-65537.lastSeen updated: ack=true; val=1520391679
tradfri.0 | 2018-03-07 13:04:36.962 | debug | state with id tradfri.0.L-65537.alive updated: ack=true; val=true
tradfri.0 | 2018-03-07 13:04:36.882 | debug | observeDevice > {"3":{"0":"IKEA of Sweden","1":"TRADFRI bulb E27 CWS opal 600lm","2":"","3":"1.3.002","6":1},"3311":[{"5706":"0","5707":43519,"5708":65279,"5709":9792,"5710":3917,"5850":1,"5851":254,
tradfri.0 | 2018-03-07 13:04:36.846 | debug | updateResource(15001/65537) > sending payload: {"3311":[{"5707":43519,"5708":65279,"5712":5}]}
tradfri.0 | 2018-03-07 13:04:36.821 | debug | updateResource(15001/65537) > comparing {"isProxy":true,"options":{},"name":"Nachttischlampe","createdAt":1510764428,"instanceId":65537,"type":2,"deviceInfo":{"isProxy":true,"options":{},"firmwareVer
tradfri.0 | 2018-03-07 13:04:36.648 | debug | state with id tradfri.0.L-65537.lightbulb.saturation updated: ack=false; val=100
tradfri.0 | 2018-03-07 13:04:28.897 | debug | ping successful...
tradfri.0 | 2018-03-07 13:04:18.902 | debug | ping successful...
tradfri.0 | 2018-03-07 13:04:09.802 | debug | object with id tradfri.0.G-131073.activeScene updated
tradfri.0 | 2018-03-07 13:04:09.791 | debug | state with id tradfri.0.G-131073.saturation updated: ack=true; val=1
tradfri.0 | 2018-03-07 13:04:09.787 | debug | state with id tradfri.0.G-131073.hue updated: ack=true; val=240
tradfri.0 | 2018-03-07 13:04:09.784 | debug | state with id tradfri.0.G-131073.color updated: ack=true; val=0000ff
tradfri.0 | 2018-03-07 13:04:09.781 | debug | state with id tradfri.0.G-131073.colorTemperature deleted
tradfri.0 | 2018-03-07 13:04:09.777 | debug | state with id tradfri.0.G-131073.brightness updated: ack=true; val=100
tradfri.0 | 2018-03-07 13:04:09.772 | debug | state with id tradfri.0.G-131073.state updated: ack=true; val=true
tradfri.0 | 2018-03-07 13:04:09.763 | debug | object with id tradfri.0.G-131073.activeScene updated
tradfri.0 | 2018-03-07 13:04:09.761 | info | received all groups and scenes
tradfri.0 | 2018-03-07 13:04:09.757 | info | updating possible scenes for group 131073: ["196608","196609","196610"]
tradfri.0 | 2018-03-07 13:04:09.704 | debug | object with id tradfri.0.G-131073.activeScene updated
tradfri.0 | 2018-03-07 13:04:09.612 | info | updating possible scenes for group 131073: ["196608","196609"]
tradfri.0 | 2018-03-07 13:04:09.496 | info | updating possible scenes for group 131073: ["196608"]
tradfri.0 | 2018-03-07 13:04:09.408 | debug | state with id tradfri.0.G-131073.saturation updated: ack=true; val=1
tradfri.0 | 2018-03-07 13:04:09.405 | debug | state with id tradfri.0.G-131073.hue updated: ack=true; val=240
tradfri.0 | 2018-03-07 13:04:09.403 | debug | state with id tradfri.0.G-131073.color updated: ack=true; val=0000ff
tradfri.0 | 2018-03-07 13:04:09.400 | debug | state with id tradfri.0.G-131073.brightness updated: ack=true; val=0
tradfri.0 | 2018-03-07 13:04:09.397 | debug | state with id tradfri.0.G-131073.state updated: ack=true; val=false
tradfri.0 | 2018-03-07 13:04:09.393 | debug | state with id tradfri.0.G-131073.activeScene updated: ack=true; val=196608
tradfri.0 | 2018-03-07 13:04:09.387 | debug | removing scenes with keys [] from group 131073
tradfri.0 | 2018-03-07 13:04:09.373 | debug | adding scenes with keys [196608,196609,196610] to group 131073
tradfri.0 | 2018-03-07 13:04:09.371 | info | got all scenes in group 131073: [196608,196609,196610]
tradfri.0 | 2018-03-07 13:04:09.299 | debug | state with id tradfri.0.L-65537.lightbulb.transitionDuration updated: ack=true; val=0.5
tradfri.0 | 2018-03-07 13:04:09.296 | debug | state with id tradfri.0.L-65537.lightbulb.state updated: ack=true; val=true
tradfri.0 | 2018-03-07 13:04:09.293 | debug | state with id tradfri.0.L-65537.lightbulb.brightness updated: ack=true; val=100
tradfri.0 | 2018-03-07 13:04:09.288 | debug | state with id tradfri.0.L-65537.lightbulb.saturation updated: ack=true; val=1
tradfri.0 | 2018-03-07 13:04:09.285 | debug | state with id tradfri.0.L-65537.lightbulb.hue updated: ack=true; val=240
tradfri.0 | 2018-03-07 13:04:09.278 | debug | state with id tradfri.0.L-65537.lightbulb.color updated: ack=true; val=0000ff
tradfri.0 | 2018-03-07 13:04:09.276 | debug | state with id tradfri.0.L-65537.lastSeen updated: ack=true; val=1520391679
tradfri.0 | 2018-03-07 13:04:09.273 | debug | state with id tradfri.0.L-65537.alive updated: ack=true; val=true
tradfri.0 | 2018-03-07 13:04:09.271 | debug | state with id tradfri.0.RC-65536.lastSeen updated: ack=true; val=1516996732
tradfri.0 | 2018-03-07 13:04:09.268 | debug | state with id tradfri.0.RC-65536.alive updated: ack=true; val=true
tradfri.0 | 2018-03-07 13:04:09.263 | debug | removing groups with keys []
tradfri.0 | 2018-03-07 13:04:09.252 | debug | adding groups with keys [131073]
tradfri.0 | 2018-03-07 13:04:09.250 | info | got all groups: [131073]
tradfri.0 | 2018-03-07 13:04:09.223 | info | received all devices
tradfri.0 | 2018-03-07 13:04:09.161 | debug | observeDevice > {"3":{"0":"IKEA of Sweden","1":"TRADFRI bulb E27 CWS opal 600lm","2":"","3":"1.3.002","6":1},"3311":[{"5706":"0","5707":43519,"5708":653,"5709":20320,"5710":21323,"5850":1,"5851":254,
tradfri.0 | 2018-03-07 13:04:09.060 | debug | observeDevice > {"3":{"0":"IKEA of Sweden","1":"TRADFRI remote control","2":"","3":"1.2.214","6":3,"9":74},"5750":0,"9001":"Nachttischlampe Fernbedienung","9002":1510764330,"9003":65536,"9019":1,"902
tradfri.0 | 2018-03-07 13:04:09.035 | debug | removing devices with keys []
tradfri.0 | 2018-03-07 13:04:09.024 | debug | adding devices with keys [65536,65537]
tradfri.0 | 2018-03-07 13:04:09.021 | info | got all devices: [65536,65537]
tradfri.0 | 2018-03-07 13:04:08.812 | debug | state with id tradfri.0.info.connection updated: ack=true; val=true
tradfri.0 | 2018-03-07 13:04:08.760 | debug | Connection successful
tradfri.0 | 2018-03-07 13:04:08.538 | debug | Attempting connection. Identity = tradfri_1519911561843, psk = 4QvoTFE5q5JluqOw
tradfri.0 | 2018-03-07 13:04:08.520 | info | startfile = /opt/iobroker/node_modules/iobroker.tradfri/main.js
tradfri.0 | 2018-03-07 13:04:08.359 | info | starting. Version 1.1.7 in /opt/iobroker/node_modules/iobroker.tradfri, node: v6.13.0
tradfri.0 | 2018-03-07 13:04:08.270 | debug | statesDB connected
tradfri.0 | 2018-03-07 13:04:08.142 | debug | objectDB connected
tradfri.0 | 2018-03-07 13:04:01.950 | debug | state with id tradfri.0.info.connection updated: ack=true; val=false



this is for restart adapter (just 1 RGB-Lamp connected to Tradfri-Bridge), then changing saturation from 1% to 100% (because it was again set to 1%) and then changing color to ff0000

**Comment by AlCalzone** [comment]
Thanks. I think you might have an outdated dependency - that 1% problem should already be fixed. Please run the following and check again if that fixes your issue:
```
cd /opt/iobroker/node_modules/iobroker.tradfri
sudo npm --depth 999 update
```

**Comment by Black-Lemon** [comment]
sadly still not working :(

**Comment by AlCalzone** [comment]
Did you restart the adapter? If yes, try a full reinstall:
```
iobroker del tradfri
cd /opt/iobroker/node_modules
rm -rf node-coap-client
rm -rf node-dtls-client
rm -rf node-aead-crypto
```
You might need to run these commands as `sudo`. Afterwards reinstall the adapter from the admin GUI.

**Comment by Black-Lemon** [comment]
Yes I did restart (and even restarted the raspbery-pi).

And tried your commands (as root), and still get 1% saturation.

**Comment by AlCalzone** [comment]
Ok, then let's check your versions again:
```
cd /opt/iobroker
npm ls | grep node-*-client
```
and once more in the adapter folder
```
cd /opt/iobroker/node_modules/iobroker.tradfri
npm ls | grep node-*-client
```

**Comment by Black-Lemon** [comment]
1.


root@raspberrypi:/opt/iobroker# npm ls | grep node-*-client
npm ERR! missing: iobroker.admin@~3.1.12, required by iobroker.inst@1.0.8
npm ERR! extraneous: async-limiter@1.0.0 /opt/iobroker/node_modules/async-limiter
npm ERR! extraneous: connect-flash@0.1.1 /opt/iobroker/node_modules/connect-flash
npm ERR! extraneous: dev-null@0.1.1 /opt/iobroker/node_modules/dev-null
npm ERR! extraneous: express@4.16.2 /opt/iobroker/node_modules/express
npm ERR! extraneous: express-fileupload@0.4.0 /opt/iobroker/node_modules/express-fileupload
npm ERR! extraneous: express-session@1.15.6 /opt/iobroker/node_modules/express-session
npm ERR! extraneous: hap-nodejs@0.4.41 /opt/iobroker/node_modules/hap-nodejs
npm ERR! extraneous: has-binary2@1.0.2 /opt/iobroker/node_modules/has-binary2
npm ERR! extraneous: iobroker.feiertage@1.0.0 /opt/iobroker/node_modules/iobroker.feiertage
npm ERR! extraneous: iobroker.fritzbox@0.3.1 /opt/iobroker/node_modules/iobroker.fritzbox
npm ERR! extraneous: iobroker.javascript@3.6.4 /opt/iobroker/node_modules/iobroker.javascript
npm ERR! extraneous: iobroker.pushover@1.0.4 /opt/iobroker/node_modules/iobroker.pushover
npm ERR! extraneous: iobroker.simple-api@1.6.2 /opt/iobroker/node_modules/iobroker.simple-api
npm ERR! extraneous: iobroker.socketio@1.8.6 /opt/iobroker/node_modules/iobroker.socketio
npm ERR! extraneous: iobroker.sonoff@1.0.2 /opt/iobroker/node_modules/iobroker.sonoff
npm ERR! extraneous: iobroker.tr-064@0.4.18 /opt/iobroker/node_modules/iobroker.tr-064
npm ERR! extraneous: iobroker.tradfri@1.1.7 /opt/iobroker/node_modules/iobroker.tradfri
npm ERR! extraneous: iobroker.yahka@0.7.1 /opt/iobroker/node_modules/iobroker.yahka
npm ERR! extraneous: macaddress@0.2.8 /opt/iobroker/node_modules/macaddress
npm ERR! extraneous: mqtt-connection@3.2.0 /opt/iobroker/node_modules/mqtt-connection
npm ERR! extraneous: node-tradfri-client@0.8.1 /opt/iobroker/node_modules/node-tradfri-client
npm ERR! extraneous: passport@0.4.0 /opt/iobroker/node_modules/passport
npm ERR! extraneous: passport-local@1.0.0 /opt/iobroker/node_modules/passport-local
npm ERR! extraneous: passport.socketio@3.7.0 /opt/iobroker/node_modules/passport.socketio
npm ERR! extraneous: pushover-notifications@0.2.4 /opt/iobroker/node_modules/pushover-notifications
npm ERR! extraneous: soef@0.4.15 /opt/iobroker/node_modules/soef
npm ERR! extraneous: tr-064@0.2.0 /opt/iobroker/node_modules/tr-064
npm ERR! extraneous: tr-O64@0.2.4 /opt/iobroker/node_modules/tr-O64
npm ERR! extraneous: util@0.10.3 /opt/iobroker/node_modules/util
npm ERR! extraneous: uws@9.14.0 /opt/iobroker/node_modules/uws



2.

root@raspberrypi:/opt/iobroker/node_modules/iobroker.tradfri# npm ls | grep node-*-client
npm ERR! missing: node-coap-client@^0.5.5, required by node-tradfri-client@0.8.5
npm ERR! missing: reflect-metadata@^0.1.12, required by node-tradfri-client@0.8.5

**Comment by AlCalzone** [comment]
Hmm, it seems like you have two versions of `node-tradfri-client` installed: 0.8.1 (which still has the bug) and 0.8.5 (which should have it fixed). Please try the fresh reinstall again, but this time also delete `node-tradfri-client`.
```
iobroker del tradfri
cd /opt/iobroker/node_modules
rm -rf iobroker.tradfri
rm -rf node-tradfri-client
rm -rf node-coap-client
rm -rf node-dtls-client
rm -rf node-aead-crypto
```

**Comment by Black-Lemon** [comment]
hmmm… still not working (restartet pi again)

that's what i get from your last commands from above:

root@raspberrypi:/opt/iobroker# npm ls | grep node-*-client
npm ERR! missing: iobroker.admin@~3.1.12, required by iobroker.inst@1.0.8
npm ERR! extraneous: async-limiter@1.0.0 /opt/iobroker/node_modules/async-limiter
npm ERR! extraneous: connect-flash@0.1.1 /opt/iobroker/node_modules/connect-flash
npm ERR! extraneous: dev-null@0.1.1 /opt/iobroker/node_modules/dev-null
npm ERR! extraneous: express@4.16.2 /opt/iobroker/node_modules/express
npm ERR! extraneous: express-fileupload@0.4.0 /opt/iobroker/node_modules/express-fileupload
npm ERR! extraneous: express-session@1.15.6 /opt/iobroker/node_modules/express-session
npm ERR! extraneous: hap-nodejs@0.4.41 /opt/iobroker/node_modules/hap-nodejs
npm ERR! extraneous: has-binary2@1.0.2 /opt/iobroker/node_modules/has-binary2
npm ERR! extraneous: iobroker.feiertage@1.0.0 /opt/iobroker/node_modules/iobroker.feiertage
npm ERR! extraneous: iobroker.fritzbox@0.3.1 /opt/iobroker/node_modules/iobroker.fritzbox
npm ERR! extraneous: iobroker.javascript@3.6.4 /opt/iobroker/node_modules/iobroker.javascript
npm ERR! extraneous: iobroker.pushover@1.0.4 /opt/iobroker/node_modules/iobroker.pushover
npm ERR! extraneous: iobroker.simple-api@1.6.2 /opt/iobroker/node_modules/iobroker.simple-api
npm ERR! extraneous: iobroker.socketio@1.8.6 /opt/iobroker/node_modules/iobroker.socketio
npm ERR! extraneous: iobroker.sonoff@1.0.2 /opt/iobroker/node_modules/iobroker.sonoff
npm ERR! extraneous: iobroker.tr-064@0.4.18 /opt/iobroker/node_modules/iobroker.tr-064
npm ERR! extraneous: iobroker.tradfri@1.1.7 /opt/iobroker/node_modules/iobroker.tradfri
npm ERR! extraneous: iobroker.yahka@0.7.1 /opt/iobroker/node_modules/iobroker.yahka
npm ERR! extraneous: macaddress@0.2.8 /opt/iobroker/node_modules/macaddress
npm ERR! extraneous: mqtt-connection@3.2.0 /opt/iobroker/node_modules/mqtt-connection
npm ERR! extraneous: node-tradfri-client@0.8.5 /opt/iobroker/node_modules/node-tradfri-client
npm ERR! extraneous: passport@0.4.0 /opt/iobroker/node_modules/passport
npm ERR! extraneous: passport-local@1.0.0 /opt/iobroker/node_modules/passport-local
npm ERR! extraneous: passport.socketio@3.7.0 /opt/iobroker/node_modules/passport.socketio
npm ERR! extraneous: pushover-notifications@0.2.4 /opt/iobroker/node_modules/pushover-notifications
npm ERR! extraneous: soef@0.4.15 /opt/iobroker/node_modules/soef
npm ERR! extraneous: tr-064@0.2.0 /opt/iobroker/node_modules/tr-064
npm ERR! extraneous: tr-O64@0.2.4 /opt/iobroker/node_modules/tr-O64
npm ERR! extraneous: util@0.10.3 /opt/iobroker/node_modules/util
npm ERR! extraneous: uws@9.14.0 /opt/iobroker/node_modules/uws



root@raspberrypi:/opt/iobroker/node_modules/iobroker.tradfri# npm ls | grep node-*-client
root@raspberrypi:/opt/iobroker/node_modules/iobroker.tradfri#

**Comment by AlCalzone** [comment]
Hmm that's weird, because I'm specifically testing for your color, and the test confirms the correct payload is being sent:
https://github.com/AlCalzone/node-tradfri-client/blob/master/src/lib/light.test.ts#L470
However your logs show another payload...

**Comment by AlCalzone** [comment]
Uhhhh... we've been chasing a ghost all the time. The change was on github before 0.8.5, but is not included in the npm package. Give me a second, sorry.

**Comment by AlCalzone** [comment]
Now try reinstalling again please.

**Comment by Black-Lemon** [comment]
Now it's working! You're great! Thank you! ; )
